#!/bin/bash

OUT_DIR=/tmp/damage-control
OUT_EXT=.out

OPTS="bmfFh"

function usage {
    echo "usage: run -$OPTS"
    echo "  b      builds"
    echo "  m      builds maven plugin"
    echo "  F      runs maven sample project and reports"
    echo "  f      runs maven reports"
    echo "  h      prints this message"
    echo

    exit -1
}

function execute_command {
    MSG=$1
    CMD=$2
    OUT=$OUT_DIR/$3$OUT_EXT

    echo -n $MSG
    $CMD &> $OUT
    RC=$?

    print_result $RC $OUT

    if [ "$RC" -ne "0" ]
    then
        exit -1
    fi
}

function print_result {
    RC=$1
    OUTFILE=$2

    if [ "$RC" -eq "0" ]
    then
        echo -e "\033[01;32m OK \033[00m"
    else
        echo -e "\033[01;31m FAILED \033[00m"
        echo "See $OUTFILE for details."
    fi
}

if [ $# -eq "0" ]
then
    usage
fi

while getopts $OPTS OPT
do
    case $OPT in
        b)
            BUILD=yes
            ;;
        m)
            MVN_PLUGIN=yes
            ;;
        f)
            RUN_MVN_SAMPLE_REPORT=yes
            ;;
        F)
            RUN_MVN_SAMPLE_TESTS=yes
            RUN_MVN_SAMPLE_REPORT=yes
            ;;
        *)
            usage
            ;;
    esac
done

if [ -e $OUT_DIR ]
then
    rm -rf $OUT_DIR/*$OUT_EXT
fi
mkdir -p $OUT_DIR

if [ $BUILD ]
then
    execute_command "Building... " "gradle test install" build
fi

if [ $MVN_PLUGIN ]
then
    cd plugins/maven
    execute_command "Building Maven Plugin... " "mvn clean install" mvn-plugin
    cd ../..
fi

if [ $RUN_MVN_SAMPLE_TESTS ]
then
    cd functional-test/sample-spock-project
    execute_command "Running Maven sample project... " "mvn clean test" mvn-sample-project
    cd ../..
fi

if [ $RUN_MVN_SAMPLE_REPORT ]
then
    cd functional-test/sample-spock-project
    execute_command "Generating Maven reports... " "mvn damage-control:report" mvn-reports
    cd ../..
fi
